
describe('Register page case - Negative', () => {

    beforeEach(() => {
        cy.visit("/register")
    })

    it('Register with blank fields', () => {
        cy.get('#first-name').should('have.attr', 'required')
        cy.get('#first-name').should('have.attr', 'type').and('match', /text/)
        cy.get('#first-name').invoke('prop', 'validationMessage')
            .should('equal', "Please fill out this field.")
        cy.get('#last-name').should('have.attr', 'required')
        cy.get('#last-name').should('have.attr', 'type').and('match', /text/)
        cy.get('#last-name').invoke('prop', 'validationMessage')
            .should('equal', "Please fill out this field.")
        cy.get('#email').should('have.attr', 'required')
        cy.get('#email').should('have.attr', 'type').and('match', /email/)
        cy.get('#email').invoke('prop', 'validationMessage')
            .should('equal', "Please fill out this field.")
        cy.get('#password').should('have.attr', 'required')
        cy.get('#password').should('have.attr', 'type').and('match', /password/)
        cy.get('#password').invoke('prop', 'validationMessage')
            .should('equal', "Please fill out this field.")
        cy.get('#password-confirmation').should('have.attr', 'required')
        cy.get('#password-confirmation').should('have.attr', 'type').and('match', /password/)
        cy.get('#password-confirmation').invoke('prop', 'validationMessage')
            .should('equal', "Please fill out this field.")
    //    cy.get(':checkbox').should('have.attr', 'required')   jel checkbox automatski required, pa ne moram ovo da pisem?
        cy.get('input:invalid').should('have.length', 5)
        cy.get('button').click()
        cy.url().should('equal', 'https://gallery-app.vivifyideas.com/register')
        cy.should('not.contain', 'Logout')
    })

    it('Register with only checkbox checked', () => {
        cy.get(':checkbox').check()
        cy.get('input:invalid').should('have.length', 5)
        cy.get('button').click()
        cy.url().should('equal', 'https://gallery-app.vivifyideas.com/register')
        cy.should('not.contain', 'Logout')
        cy.get('#first-name').invoke('prop', 'validationMessage')
            .should('equal', "Please fill out this field.")
    })

    it('Fill out everything except the First name', () => {
        cy.get('#last-name').type('Petrovic')
        cy.get('#email').type('nebopajo2@gmail.com')
        cy.get('#password').type('nebopajo123')
        cy.get('#password-confirmation').type('nebopajo123')
        cy.get(':checkbox').check()
        cy.get('button').click()
        cy.get('.nav-link').should('have.length', 3)
        cy.url().should('not.contain', '/logout')
        cy.url().should('equal', 'https://gallery-app.vivifyideas.com/register')
        cy.get('#first-name').invoke('prop', 'validationMessage')
            .should('equal', "Please fill out this field.")
    })

    it('Fill out everything except the Last name', () => {
        cy.get('#first-name').type('Petar')
        cy.get('#email').type('nebopajo2@gmail.com')
        cy.get('#password').type('nebopajo123')
        cy.get('#password-confirmation').type('nebopajo123')
        cy.get(':checkbox').check()
        cy.get('button').click()
        cy.get('.nav-link').should('have.length', 3)
        cy.url().should('not.contain', '/logout')
        cy.url().should('equal', 'https://gallery-app.vivifyideas.com/register')
        cy.get('#last-name').invoke('prop', 'validationMessage')
            .should('equal', "Please fill out this field.")
    })

    it('Fill out everything except the email', () => {
        cy.get('#first-name').type('Petar')
        cy.get('#last-name').type('Petrovic')
        cy.get('#password').type('nebopajo123')
        cy.get('#password-confirmation').type('nebopajo123')
        cy.get(':checkbox').check()
        cy.get('button').click()
        cy.get('.nav-link').should('have.length', 3)
        cy.url().should('not.contain', '/logout')
        cy.url().should('equal', 'https://gallery-app.vivifyideas.com/register')
        cy.get('#email').invoke('prop', 'validationMessage')
            .should('equal', "Please fill out this field.")
    })

    it('Fill out everything except the password', () => {
        cy.get('#first-name').type('Petar')
        cy.get('#last-name').type('Petrovic')
        cy.get('#email').type('nebopajo2@gmail.com')
        cy.get('#password-confirmation').type('nebopajo123')
        cy.get(':checkbox').check()
        cy.get('button').click()
        cy.get('.nav-link').should('have.length', 3)
        cy.url().should('not.contain', '/logout')
        cy.url().should('equal', 'https://gallery-app.vivifyideas.com/register')
        cy.get('#password').invoke('prop', 'validationMessage')
            .should('equal', "Please fill out this field.")
    })

    it('Fill out everything and dont confirm the password', () => {
        cy.get('#first-name').type('Petar')
        cy.get('#last-name').type('Petrovic')
        cy.get('#email').type('nebopajo2@gmail.com')
        cy.get('#password').type('nebopajo123')
        cy.get(':checkbox').check()
        cy.get('button').click()
        cy.get('.nav-link').should('have.length', 3)
        cy.url().should('not.contain', '/logout')
        cy.url().should('equal', 'https://gallery-app.vivifyideas.com/register')
        cy.get('#password-confirmation').invoke('prop', 'validationMessage')
            .should('equal', "Please fill out this field.")
    })

    it('Fill out everything and dont check the checkbox', () => {
        cy.get('#first-name').type('Petar')
        cy.get('#last-name').type('Petrovic')
        cy.get('#email').type('nebopajo2@gmail.com')
        cy.get('#password').type('nebopajo123')
        cy.get('#password-confirmation').type('nebopajo123')
        cy.get('button').click()
        cy.get('.nav-link').should('have.length', 3)
        cy.url().should('not.contain', '/logout')
        cy.url().should('equal', 'https://gallery-app.vivifyideas.com/register')
        cy.get('.alert').should('be.visible')
    })

    it('Register with a non email', () => {
        cy.get('#first-name').type('Petar')
        cy.get('#last-name').type('Petrovic')
        cy.get('#email').type('nebopajo@gmaill.coooom')   // ovaj test bi trebao da padne, ali uspeva da prihvati email
        cy.get('#password').type('nebopajo123')
        cy.get('#password-confirmation').type('nebopajo123')
        cy.get(':checkbox').check()
        cy.get('button').click()
        cy.get('.nav-link').should('have.length', 3)
        cy.url().should('not.contain', '/logout')
        cy.url().should('equal', 'https://gallery-app.vivifyideas.com/register')
        cy.get('.alert').should('be.visible')
    })

    it('Register with a non-existing email', () => {
        cy.get('#first-name').type('Petar')
        cy.get('#last-name').type('Petrovic')
        cy.get('#email').type('nebopajo7@gmail.com')   // takodje i ovaj test bi trebao da padne, ali prolazi
        cy.get('#password').type('nebopajo123')       // kako uopste moze da se zna da je email nepostojeci?
        cy.get('#password-confirmation').type('nebopajo123')
        cy.get(':checkbox').check()
        cy.get('button').click()
        cy.get('.nav-link').should('have.length', 3)
        cy.url().should('not.contain', '/logout')
        cy.url().should('equal', 'https://gallery-app.vivifyideas.com/register')
        cy.get('.alert').should('be.visible')
    })

    it('Register with an already registered email', () => {
        cy.get('#first-name').type('Petar')
        cy.get('#last-name').type('Petrovic')
        cy.get('#email').type('nadjlukac.test@gmail.com')
        cy.get('#password').type('nebopajo123')
        cy.get('#password-confirmation').type('nebopajo123')
        cy.get(':checkbox').check()
        cy.get('button').click()
        cy.get('.nav-link').should('have.length', 3)
        cy.url().should('not.contain', '/logout')
        cy.url().should('equal', 'https://gallery-app.vivifyideas.com/register')
        cy.get('.alert').should('be.visible')
    })

    it('Password with 7 characters (no digit)', () => {
        cy.get('#first-name').type('Petar')
        cy.get('#last-name').type('Petrovic')
        cy.get('#email').type('nebopajo2@gmail.com')
        cy.get('#password').type('nebopaj')
        cy.get('#password-confirmation').type('nebopaj')
        cy.get(':checkbox').check()
        cy.get('button').click()
        cy.get('.nav-link').should('have.length', 3)
        cy.url().should('not.contain', '/logout')
        cy.url().should('equal', 'https://gallery-app.vivifyideas.com/register')
        cy.get('.alert').should('be.visible')
    })

    it('Password with 7 characters (1 of them a digit)', () => {
        cy.get('#first-name').type('Petar')
        cy.get('#last-name').type('Petrovic')
        cy.get('#email').type('nebopajo2@gmail.com')
        cy.get('#password').type('nebopa1')
        cy.get('#password-confirmation').type('nebopa1')
        cy.get(':checkbox').check()
        cy.get('button').click()
        cy.get('.nav-link').should('have.length', 3)
        cy.url().should('not.contain', '/logout')
        cy.url().should('equal', 'https://gallery-app.vivifyideas.com/register')
        cy.get('.alert').should('be.visible')
    })

    it('Password with 8 characters (no digit)', () => {
        cy.get('#first-name').type('Petar')
        cy.get('#last-name').type('Petrovic')
        cy.get('#email').type('nebopajo2@gmail.com')
        cy.get('#password').type('nebopajo')
        cy.get('#password-confirmation').type('nebopajo')
        cy.get(':checkbox').check()
        cy.get('button').click()
        cy.get('.nav-link').should('have.length', 3)
        cy.url().should('not.contain', '/logout')
        cy.url().should('equal', 'https://gallery-app.vivifyideas.com/register')
        cy.get('.alert').should('be.visible')
    })

    it('Successfull registration', () => {
        cy.get('#first-name').type('Petar')
        cy.get('#last-name').type('Petrovic')
        cy.get('#email').type('nebopajo1@gmail.com')
        cy.get('#password').type('nebopajo123')
        cy.get('#password-confirmation').type('nebopajo123')
        cy.get(':checkbox').check()
        cy.get('button').click()
        cy.get('.nav-link').should('have.length', 4)
        cy.url().should('not.contain', '/login')
        cy.url().should('equal', 'https://gallery-app.vivifyideas.com/')
    })
})
